glslc.exe ./basicUpdated.frag -o basic_updated_frag.spv
glslc.exe ./basicInstanced.vert -o basic_instanced_vert.spv
glslc.exe ./culledInstanced.vert -o culled_instanced_vert.spv
glslc.exe ./culling.comp -o culling_comp.spv
glslc.exe ./reduceDepth.comp -o reduce_depth_comp.spv
glslc.exe ./screenQuad.vert -o screen_quad_vert.spv
glslc.exe ./gbuffer.frag -o gbuffer_frag.spv
glslc.exe ./basicDeferred.frag -o basic_deferred_frag.spv
glslc.exe ./pbrForward.frag -o pbr_forward_frag.spv
glslc.exe ./pbrDeferred.frag -o pbr_deferred_frag.spv